<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @OA\Schema(
 *    schema="VendasVendedor",
 *    @OA\Property(
 *        property="id",
 *        type="integer",
 *        description="ID do registro",
 *        nullable=false,
 *        example="1"
 *    ),
 *    @OA\Property(
 *        property="data",
 *        type="string",
 *        description="",
 *        nullable=false,
 *        format="date-time"
 *    ),
 *    @OA\Property(
 *        property="mes",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example="12"
 *    ),
 *    @OA\Property(
 *        property="ano",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example="2025"
 *    ),
 *    @OA\Property(
 *        property="cnpj_empresa",
 *        type="string",
 *        description="",
 *        nullable=false,
 *        example="39311444000183"
 *    ),
 *    @OA\Property(
 *        property="codigo_vendedor",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_quant",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_bruto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_desconto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_liquido",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_por_venda",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_dif_venda",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_quant_vendas",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_quant",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_taxa",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_produto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_servico",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_total",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_cmv",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="desp_var",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="desp_fixo",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_contrib",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_contrib_perc",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_bruto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_bruta",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_estimado",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_pe",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="ticket_medio",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_dinh",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_cheq",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_boleto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_c_cred",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_c_deb",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_crediario",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_vale",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_depcc",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_pix",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="estoque_medio",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_incluidos",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_perdidos",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_perdidos_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_faturados",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_faturados_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_taxa_conver",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 * )
 *
 *
 * * @OA\Schema(
 *    schema="VendasVendedorWithDate",
 *    @OA\Property(
 *        property="id",
 *        type="integer",
 *        description="ID do registro",
 *        nullable=false,
 *        example="1"
 *    ),
 *    @OA\Property(
 *        property="data",
 *        type="string",
 *        description="",
 *        nullable=false,
 *        format="date-time"
 *    ),
 *    @OA\Property(
 *        property="mes",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example="12"
 *    ),
 *    @OA\Property(
 *        property="ano",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example="2025"
 *    ),
 *    @OA\Property(
 *        property="cnpj_empresa",
 *        type="string",
 *        description="",
 *        nullable=false,
 *        example="39311444000183"
 *    ),
 *    @OA\Property(
 *        property="codigo_vendedor",
 *        type="integer",
 *        description="",
 *        nullable=false,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_quant",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_bruto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_desconto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="vendas_liquido",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_por_venda",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_dif_venda",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="itens_quant_vendas",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_quant",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="devolucoes_taxa",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_produto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_servico",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_total",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="faturado_cmv",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="desp_var",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="desp_fixo",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_contrib",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_contrib_perc",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_bruto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="margem_bruta",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_estimado",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="lucro_pe",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="ticket_medio",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_dinh",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_cheq",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_boleto",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_c_cred",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_c_deb",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_crediario",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_vale",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_depcc",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="tpag_pix",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="estoque_medio",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_incluidos",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_perdidos",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_perdidos_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_faturados",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_faturados_valor",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="dav_taxa_conver",
 *        type="numeric",
 *        description="",
 *        nullable=true,
 *        example=""
 *    ),
 *    @OA\Property(
 *        property="created_at",
 *        type="string",
 *        description="Data da criacao da empresa",
 *        nullable=false,
 *        format="date-time"
 *    ),
 *    @OA\Property(
 *        property="updated_at",
 *        type="string",
 *        description="Data da ultima alteracao da empresa",
 *        nullable=false,
 *        format="date-time"
 *    ),
 * )
 *
 */

class VendasVendedor extends Model
{
    protected $table = 'vendas_vendedor';

    protected $fillable = [
        'id',
        'data',
        'mes',
        'ano',

        'cnpj_empresa',        // cnpj da empresa que pertence o registro
        'codigo_vendedor',      // codigo vendedor alfa

        'vendas_quant',        // numero de vendas ocorridas nesta data
        'vendas_bruto',        // (somente vendas)
        'vendas_desconto',     // (somente vendas)
        'vendas_liquido',      // (somente vendas - desconto)
        'itens_por_venda',     // unidades por transação (media de itens por venda) (upt)
        'itens_dif_venda',     // numero de produtos diferentes vendidos nesta data
        'itens_quant_vendas',  // soma de todas as quantidades vendidas nesta data
        'devolucoes_quant',    // numero de devoluções ocorridas nesta data
        'devolucoes_valor',    //
        'devolucoes_taxa',     // (%) - devoluções / total_faturado
        'faturado_produto',    //
        'faturado_servico',    //
        'faturado_total',      // (vendaliquida - descontos)
        'faturado_cmv',        // custo da mercadoria vendida (faturada)
        'desp_var',            // valor estimado das despesas variaveis das vendas desta data
        'desp_fixo',           // valor estimado das despesas fixas das vendas desta data
        'margem_contrib',      // margem de contribuição do dia = vendas do dia-(custos variáveis do dia+despesas variáveis do dia) - esse valor é quanto o dia contribuiu para cobrir fixos e lucro.
        'margem_contrib_perc', // (%) -> margem_contrib_per = (margem_contrib / total_faturado) x 100 - assim você enxerga, por exemplo, que “neste dia, 35% do que foi vendido ficou para cobrir fixos e gerar lucro
        'lucro_bruto',         //
        'margem_bruta',        // margem bruta = lucro bruto/total_faturado x 100
        'lucro_estimado',      // margem de lucro líquida
        'lucro_pe',            //
        'ticket_medio',        //
        'tpag_dinh',           //
        'tpag_cheq',           //
        'tpag_boleto',         //
        'tpag_c_cred',         //
        'tpag_c_deb',          //
        'tpag_crediario',      //
        'tpag_vale',           //
        'tpag_depcc',          //
        'tpag_pix',            //
        'estoque_medio',       // valor do custo do estoque físico total da loja (medir giro do estoque)
        'dav_incluidos',       // numero total de orçamentos incluidos nesta data
        'dav_perdidos',        // numero orçamentos perdidos nesta data
        'dav_perdidos_valor',  // valor total de dav perdidos nesta data
        'dav_faturados',       // numero orçamentos convertidos em venda nesta data
        'dav_faturados_valor', // valor total de dav faturados nesta data
        'dav_taxa_conver',     // % de atendimento convertido em vendas (dav_faturados + vendas que não foram originadas de davs) / (num_dav_faturados + num_dav_incluidos + num_dav_perdidos - num_vendas) (da mesma data)cientes_quant       //
    ];

    use HasFactory;
}
